// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::article_removed_from_blog {

    use sui::object::{Self, ID};
    use sui_blog_example::blog::{Self, ArticleRemovedFromBlog};

    public fun id(article_removed_from_blog: &ArticleRemovedFromBlog): object::ID {
        blog::article_removed_from_blog_id(article_removed_from_blog)
    }

    public fun article_id(article_removed_from_blog: &ArticleRemovedFromBlog): ID {
        blog::article_removed_from_blog_article_id(article_removed_from_blog)
    }

}
