// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::article_tags_updated {

    use std::string::String;
    use sui::object;
    use sui_blog_example::article::{Self, ArticleTagsUpdated};

    public fun id(article_tags_updated: &ArticleTagsUpdated): object::ID {
        article::article_tags_updated_id(article_tags_updated)
    }

    public fun tags(article_tags_updated: &ArticleTagsUpdated): vector<String> {
        article::article_tags_updated_tags(article_tags_updated)
    }

}
