// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::blog_created {

    use std::option;
    use std::string::String;
    use sui::object::{Self, ID};
    use sui_blog_example::blog::{Self, BlogCreated};

    public fun id(blog_created: &BlogCreated): option::Option<object::ID> {
        blog::blog_created_id(blog_created)
    }

    public fun name(blog_created: &BlogCreated): String {
        blog::blog_created_name(blog_created)
    }

    public fun articles(blog_created: &BlogCreated): vector<ID> {
        blog::blog_created_articles(blog_created)
    }

}
