// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::blog_aggregate {
    use std::string::String;
    use sui::object::ID;
    use sui::tx_context;
    use sui_blog_example::blog;
    use sui_blog_example::blog_update_logic;

    friend sui_blog_example::article_create_logic;
    friend sui_blog_example::article_delete_logic;

    public entry fun update(
        blog: blog::Blog,
        name: String,
        articles: vector<ID>,
        ctx: &mut tx_context::TxContext,
    ) {
        let blog_updated = blog_update_logic::verify(
            name,
            articles,
            &blog,
            ctx,
        );
        let updated_blog = blog_update_logic::mutate(
            &blog_updated,
            blog,
            ctx,
        );
        blog::update_version_and_transfer_object(updated_blog, tx_context::sender(ctx));
        blog::emit_blog_updated(blog_updated);
    }

}
