// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::blog_updated {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_blog_example::blog::{Self, BlogUpdated};

    public fun id(blog_updated: &BlogUpdated): object::ID {
        blog::blog_updated_id(blog_updated)
    }

    public fun name(blog_updated: &BlogUpdated): String {
        blog::blog_updated_name(blog_updated)
    }

    public fun articles(blog_updated: &BlogUpdated): vector<ID> {
        blog::blog_updated_articles(blog_updated)
    }

}
