// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module SuiBlogExample::comment_added {

    use std::string::String;
    use sui::object;
    use SuiBlogExample::article::{Self, CommentAdded};

    public fun id(comment_added: &CommentAdded): object::ID {
        article::comment_added_id(comment_added)
    }

    public fun comment_seq_id(comment_added: &CommentAdded): u64 {
        article::comment_added_comment_seq_id(comment_added)
    }

    public fun commenter(comment_added: &CommentAdded): String {
        article::comment_added_commenter(comment_added)
    }

    public fun body(comment_added: &CommentAdded): String {
        article::comment_added_body(comment_added)
    }

}
