// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::donation_received {

    use sui::object;
    use sui_blog_example::blog::{Self, DonationReceived};

    public fun id(donation_received: &DonationReceived): object::ID {
        blog::donation_received_id(donation_received)
    }

    public fun amount(donation_received: &DonationReceived): u64 {
        blog::donation_received_amount(donation_received)
    }

}
