// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::tag_v2_aggregate {
    use std::string::String;
    use sui::tx_context;
    use sui_blog_example::tag_v2;
    use sui_blog_example::tag_v2_create_logic;

    public entry fun create(
        name: String,
        ctx: &mut tx_context::TxContext,
    ) {
        let tag_v2_created = tag_v2_create_logic::verify(
            name,
            ctx,
        );
        let tag_v2 = tag_v2_create_logic::mutate(
            &tag_v2_created,
            ctx,
        );
        tag_v2::set_tag_v2_created_id(&mut tag_v2_created, tag_v2::id(&tag_v2));
        tag_v2::freeze_object(tag_v2);
        tag_v2::emit_tag_v2_created(tag_v2_created);
    }

}
