// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_blog_example::tag_v2_created {

    use std::option;
    use std::string::String;
    use sui::object;
    use sui_blog_example::tag_v2::{Self, TagV2Created};

    public fun id(tag_v2_created: &TagV2Created): option::Option<object::ID> {
        tag_v2::tag_v2_created_id(tag_v2_created)
    }

    public fun name(tag_v2_created: &TagV2Created): String {
        tag_v2::tag_v2_created_name(tag_v2_created)
    }

}
