spring:
  datasource:
    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 1024

sui:
  contract:
    jsonrpc:
      #url: "https://fullnode.devnet.sui.io/"
      #url: "https://fullnode.testnet.sui.io/"
      #url: "http://localhost:9000"
      url: "https://sui.devnet.m2.movementlabs.xyz:443/"
    #package-publish-transaction: "FE9c2a7UAwefd4AhCh19sdGkpzChaaQ3eEScrjY1WrzP"
    package-publish-transaction: "atVnUPbf4jSoPU1wiKw1RG6wfCQbk1vQatGvuLFcRo7"
#    pull-day-summary-events:
#      day-summary-created:
#        fixed-delay: 6000
#    pull-order-v2-events:
#      order-v2-created:
#        fixed-delay: 6000
